name: commonz
favicon: null
layout_spectrum: 0.60998
typography_spectrum: 0
title: 'creative commonz '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#ccc8c7'
    - '#0b0a0c'
    - '#9a9695'
    - '#6c6970'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
