name: commonz
favicon: null
layout_spectrum: 0.60998
typography_spectrum: 0
title: 'creative commonz '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece9ec'
    - '#111916'
    - '#97a399'
    - '#6e4b20'
    - '#223e32'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
