name: commonz
favicon: null
layout_spectrum: 0.60998
typography_spectrum: 0
title: 'creative commonz '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecedef'
    - '#837f74'
    - '#aca9a2'
    - '#000000'
    - '#332e2b'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
